apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-shopping-cart-deployment
  labels:
    app: docker-k8s-shopping-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-k8s-shopping-cart
  template:
    metadata:
      labels:
        app: docker-k8s-shopping-cart
    spec:
      containers:
        - name : docker-k8s-shopping-cart
          image : maleesha96/shopping-cart-action
          imagePullPolicy: Always
          ports:
            - containerPort: 6091