server:
  port: 9092
  servlet:
    context-path: /api/v1/item-management-service

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/ctse
#    username: root
#    password:
    url: jdbc:mysql://194.233.72.202:3306/sales_inventory
    username: sales_inventory_user
    password: dFV@X@L7hyaSF5
